### ISSUE TITLE
PID Autotune wrong Setpoint

### ISSUE THREAD

**Issue by Malord958** [vitotai/BrewManiacEsp8266#106]
In manual mode, starting autotune changes the target temperature to the current temperature. (setpoint=CurrentTemperature instead of setpoint=SettingTemperature). Tested with version 0.5.1 (bin file). 
maybe the cause of issue #93? behavior is the same
![photo_2022-04-06_21-45-11](https://user-images.githubusercontent.com/64158451/162058534-306e9222-6d9b-4508-88e7-eb668043663a.jpg)
![photo_2022-04-06_21-45-18](https://user-images.githubusercontent.com/64158451/162058570-05d228d7-a52a-4589-b8c2-ff5484fd93eb.jpg)
.

**Comment by vitotai** [comment]
The target temperature of autotune is the temperature reading when you start, not the setting temperature.

**Comment by Malord958** [comment]
OK sorry. The screenshots in the documentation made me think there was a issue.
![image](https://user-images.githubusercontent.com/64158451/164985349-8cfd77d3-6212-4a1b-ae0d-56135b0c7929.png)
https://github.com/vitotai/BrewManiacEsp8266/blob/master/docs/UserManual/3.ManualModeAndAutoTune.md
