### ISSUE TITLE
'PCF8574' does not name a type

### ISSUE THREAD

**Issue by arudmin** [vitotai/BrewManiacEsp8266#12]
Arduino: 1.8.1 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from sketch/BrewManiac.cpp:17:0:
pins.h:75: error: 'PCF8574' does not name a type
 PCF8574 pcf8574(PCF8574_ADDRESS, I2C_SDA, I2C_SCL);
 ^
sketch/pins.h: In function 'void btnPrepareRead()':
pins.h:91: error: 'pcf8574' was not declared in this scope
  _portvalue=pcf8574.read8();
             ^
In file included from sketch/BrewManiac.cpp:313:0:
sketch/ui.h: In function 'void uiScanLcdAddress()':
ui.h:302: error: 'class LiquidCrystal_I2C' has no member named 'updateAddress'
     lcd.updateAddress(address);
         ^
exit status 1
'PCF8574' does not name a type

![screenshot 2017-08-11 18 33 55](https://user-images.githubusercontent.com/966382/29221847-ef50e162-7ec8-11e7-9a66-a18e0c784f42.jpg)

**Comment by vitotai** [comment]
Download the libraries from here:
https://github.com/vitotai/BrewManiacEsp8266/tree/master/libs

Or, use PlatformIO and download this branch:
https://github.com/vitotai/BrewManiacEsp8266/tree/master/libs

I no longer use Arduino IDE.

**Comment by allthepies** [comment]
https://github.com/vitotai/BrewManiacEsp8266/issues/4

Switch to PlatformIO :+1:    or use Vito's libraries.

**Comment by arudmin** [comment]
Thanks, I've replaced LC and PCF8574 libs from archive and compiling done.

**Comment by NixxBr** [comment]
Sorry for the old age topic, but i am receive the same error ("PCF8574 does not name a type"). The links for download the libraries was broken (page not found).

Please Vitotai, can you check ?

**Comment by vitotai** [comment]
The libraries should be downloaded why you download the whole project, or it doesn't?
https://github.com/vitotai/BrewManiacEsp8266/tree/master/lib
