### ISSUE TITLE
Mash out setting when recipe imported

### ISSUE THREAD

**Issue by allthepies** [vitotai/BrewManiacEsp8266#15]
Hi Vito,

When importing a BeerXML recipe which has a mash out step defined, BMEx is adding another mash out step as per the recipe options settings.  Could you add an option in the recipes section to use mash out steps from the BeerXML ?  I know you did something similar for the mash-in temperature setting.

Thanks!   Myself and a brewing mate have built a Braumeister replacement controller using BMEx this weekend.  Works really well and my mate is very impressed.

**Comment by vitotai** [comment]
What is the temperature of Mashout in your BeerXML?
If the temperature of last mash step is greater or equal to 75C, it is regarded as MashOut. 

Check this code:
`
if(mashes[mashes.length -1].temp >= 75){
		mashOut=true;
		mashes[mashes.length -1].aname = "Mash Out";
	}else
		mashOut=false;
	var step=1;
// [code deleted for better illustration]
	if(!mashOut)
		nmashes.push({aname:"Mash Out",temp:this.opt.MashOutTemp,time:this.opt.MashOutTime});
`

BrewManiacEx requires mandatory Mash Out rest. I followed the design of OpenArdBir, although the code was written from scratch.

**Comment by allthepies** [comment]
Good question!  I can't remember.

So if BeerXML contains a step with a temp >- 75 degC then it will be treated as a Mash Out.  Will the "default" mash out as defined in the Recipes/options config of BMEx be ignored if a Mash Out is detected in BeerXML ?   I was getting the BeerXML mashout and then the additional mash out with BMEx had added.   Obviously I only want one.

**Comment by vitotai** [comment]
yes. The default Mashout is inserted only when there's none in the BeerXML.

If you can provide me the BeerXML, it might help.

**Comment by allthepies** [comment]
OK, I'll get hold of the BeerXML we used.

**Comment by allthepies** [comment]
Mash out temp was 55 degC (we were testing)  so the s/w added the default mash out.

<INFUSE_TEMP>55.0 C</INFUSE_TEMP>
