### ISSUE TITLE
Typo in HTML element class name

### ISSUE THREAD

**Issue by allthepies** [vitotai/BrewManiacEsp8266#18]
https://github.com/vitotai/BrewManiacEsp8266/blob/50f790a6c3d7ea5c382f8b1879329ebfbc2ed994/data/index.htm#L561

"perfer_infuse" should be "prefer_infuse".  This results in the JQuery.onChange event not firing.

**Comment by vitotai** [comment]
Thanks.

**Comment by allthepies** [comment]
Working now, thanks.
