### ISSUE TITLE
Issue with sparge heating control.

### ISSUE THREAD

**Issue by lekrom** [vitotai/BrewManiacEsp8266#37]
Hi Vito. Found a bug with sparge heating. As soon as i enter auto mode, sparge heater is turned on and stays on. The lcd as well as lcd on web interface does not update the sparge temp in auto mode, frozen at last temp reading prior to entering auto mode. The temp #2 box on web interface does however seem to show correctly.

**Comment by lekrom** [comment]
Sparge kettle was boiling @95 deg C while mashing. (typicall for my altitude) it was set to 75 (mash out)

**Comment by lekrom** [comment]
Figured it out, I think. Think the eprom was not set up correctly after upgrading. Saving settings from lcd menu fixed it.

**Comment by at001984** [comment]
how did you solve the problem?

**Comment by lekrom** [comment]
This problem has popped up again. Not sure how to fix
