### ISSUE TITLE
Problem to get it to work

### ISSUE THREAD

**Issue by RadioDJ** [vitotai/BrewManiacEsp8266#41]
I have some problem with your software.
When I compile it in Arduino IDE I get this:
pins.h:88: error: invalid conversion from 'int' to 'TwoWire*' [-fpermissive]

I have tried several things but nothing helps.
It seems that I have problem to load the pcf8574_esp files.
Any idea what I'm doing wrong?

**Comment by allthepies** [comment]
You need to use PlatformIO not the Arduino IDE, the project moved away from Arduino some time ago.

**Comment by RadioDJ** [comment]
Ok.
Thats why.
I shall try PlatformIO instead.
Thank you.
